### PR TITLE
Editor finished

### PR DESCRIPTION
**Pull request by christopherWilliams98**
The editor is now functional, albeit really simple.

### CODE REVIEW

**Review by NoeTerrier — COMMENTED** [review]
I tried to build and run the app but I got an error while clicking on a file "new score" in the list of notes. The app crash with this stacktrace:

`FATAL EXCEPTION: alphaTabRenderThread
                                                                                                    Process: com.github.scribeWizTeam.scribewiz, PID: 7990
                                                                                                    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                                                                    	at java.util.ArrayList.get(ArrayList.java:437)
                                                                                                    	at alphaTab.collections.List.get(List.kt:51)
                                                                                                    	at alphaTab.rendering.layout.ScoreLayout.createScoreInfoGlyphs(ScoreLayout.kt:178)
                                                                                                    	at alphaTab.rendering.layout.ScoreLayout.layoutAndRender(ScoreLayout.kt:90)
                                                                                                    	at alphaTab.rendering.ScoreRenderer.layoutAndRender(ScoreRenderer.kt:281)
                                                                                                    	at alphaTab.rendering.ScoreRenderer.render(ScoreRenderer.kt:246)
                                                                                                    	at alphaTab.rendering.ScoreRenderer.resizeRender(ScoreRenderer.kt:259)
                                                                                                    	at alphaTab.platform.android.AndroidThreadScoreRenderer.resizeRender(AndroidThreadScoreRenderer.kt:116)
                                                                                                    	at alphaTab.platform.android.AndroidThreadScoreRenderer$resizeRender$1.invoke(AndroidThreadScoreRenderer.kt:118)
                                                                                                    	at alphaTab.platform.android.AndroidThreadScoreRenderer$resizeRender$1.invoke(AndroidThreadScoreRenderer.kt:118)
                                                                                                    	at alphaTab.platform.android.AndroidThreadScoreRenderer.run(AndroidThreadScoreRenderer.kt:51)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`

**Comment by christopherWilliams98** [comment]
> I tried to build and run the app but I got an error while clicking on a file "new score" in the list of notes. The app crash with this stacktrace:
> 
> `FATAL EXCEPTION: alphaTabRenderThread Process: com.github.scribeWizTeam.scribewiz, PID: 7990 java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 at java.util.ArrayList.get(ArrayList.java:437) at alphaTab.collections.List.get(List.kt:51) at alphaTab.rendering.layout.ScoreLayout.createScoreInfoGlyphs(ScoreLayout.kt:178) at alphaTab.rendering.layout.ScoreLayout.layoutAndRender(ScoreLayout.kt:90) at alphaTab.rendering.ScoreRenderer.layoutAndRender(ScoreRenderer.kt:281) at alphaTab.rendering.ScoreRenderer.render(ScoreRenderer.kt:246) at alphaTab.rendering.ScoreRenderer.resizeRender(ScoreRenderer.kt:259) at alphaTab.platform.android.AndroidThreadScoreRenderer.resizeRender(AndroidThreadScoreRenderer.kt:116) at alphaTab.platform.android.AndroidThreadScoreRenderer$resizeRender$1.invoke(AndroidThreadScoreRenderer.kt:118) at alphaTab.platform.android.AndroidThreadScoreRenderer$resizeRender$1.invoke(AndroidThreadScoreRenderer.kt:118) at alphaTab.platform.android.AndroidThreadScoreRenderer.run(AndroidThreadScoreRenderer.kt:51) at java.lang.Thread.run(Thread.java:1012)`

I also have the same proble, but I assume that this is a problem with the score itself as it is a null file as far as I know. If you try to make a new recording and then edit that score it should work as normal!

**Review by NoeTerrier — APPROVED** [review]
Nice ! Maybe a next task could be to refined the UI, maybe with a keyboard with all the notes instead of a scrollable menu,  center all this and why not merging it with the rec fragment to edit directly after recording it.

**Comment by christopherWilliams98** [comment]
> Nice ! Maybe a next task could be to refined the UI, maybe with a keyboard with all the notes instead of a scrollable menu, center all this and why not merging it with the rec fragment to edit directly after recording it.

Good ideas, I will try to implement this next sprint!

**Pull request merged**
